name: LionECS
attributes:
  ORGANIZATIONNAME: Lion Software Tomasz Lewandowski
options:
  createIntermediateGroups: true
  xcodeVersion: 11.3
  groupSortPosition: top
  deploymentTarget:
    iOS: "13.0"
    macOS: "10.15"
configs:
  Debug: debug
  Release: release
fileGroups:
  - Configurations
  - Package.swift
configFiles:
  Debug: Configurations/Debug.xcconfig
  Release: Configurations/Release.xcconfig
schemes:
  LionECS_iOS:
    build:
      targets:
        LionECS_iOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets: [LionECSTests_iOS]
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  LionECS_macOS:
    build:
      targets:
        LionECS_macOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets: [LionECSTests_macOS]
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  LionECS_watchOS:
    build:
      targets:
        LionECS_watchOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets: []
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  LionECS_tvOS:
    build:
      targets:
        LionECS_tvOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets: [LionECSTests_tvOS]
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  LionECS:
    type: framework
    platform: [macOS, iOS, tvOS, watchOS]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(ECS_BUNDLE_IDENTIFIER)
        PROVISIONING_PROFILE_SPECIFIER: $(ECS_PROVISIONING_PROFILE_SPECIFIER)
    sources:
      - path: ECS
  LionECSTests:
    type: bundle.unit-test
    platform: [macOS, iOS, tvOS]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.lionsoftware.lionengine.ecs.tests
        # empty specifier resolves to "Automatic"
        PROVISIONING_PROFILE_SPECIFIER: 
    sources:
      - path: ECSTests
    dependencies:
      - target: LionECS_macOS
  Example:
    type: tool
    platform: macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.lionsoftware.lionengine.ecs.example
        # empty specifier resolves to "Automatic"
        PROVISIONING_PROFILE_SPECIFIER:
        CURRENT_PROJECT_VERSION: 1
    sources:
      - path: Example
    dependencies:
      - target: LionECS_macOS
    postBuildScripts:
      - script: |
                "${PODS_ROOT}/SwiftLint/swiftlint"
        name: SwiftLint